# Generated by Django 4.1.2 on 2022-11-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conf',
            old_name='user_db',
            new_name='user_db_kontur',
        ),
    ]
