# Generated by Django 4.1.2 on 2022-11-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_rename_user_db_conf_user_db_kontur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf',
            name='password_ssh',
            field=models.CharField(max_length=250, verbose_name='пароль для доступа по ssh к балону'),
        ),
    ]
