# Generated by Django 4.1.2 on 2022-11-11 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.position', verbose_name='должность'),
        ),
    ]
