# Generated by Django 4.1.2 on 2022-11-11 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_position_name_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'уровень доступа', 'verbose_name_plural': 'уровни доступа'},
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=150, verbose_name='уровень доступа'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.position', verbose_name='уровень доступа'),
        ),
    ]
