# Generated by Django 4.1.2 on 2022-11-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bill', models.DateTimeField()),
                ('id_ticket', models.CharField(max_length=200)),
                ('tariff', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'таблица контур',
                'verbose_name_plural': 'таблицы контура',
            },
        ),
        migrations.CreateModel(
            name='Kontur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bill', models.DateTimeField()),
                ('id_ticket', models.CharField(max_length=200)),
                ('tariff', models.CharField(max_length=200)),
                ('ticket_validity_date', models.DateTimeField()),
                ('date_of_ticket_passage', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'таблица контур',
                'verbose_name_plural': 'таблицы контура',
            },
        ),
    ]
