# Generated by Django 4.1.2 on 2022-12-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformationAboutTheDeskRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_a', models.CharField(blank=True, max_length=250, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bill', models.CharField(blank=True, max_length=250, null=True)),
                ('id_ticket', models.CharField(blank=True, max_length=200, null=True)),
                ('tariff', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecodingOfDeskSectionsAndTaxGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_group', models.CharField(blank=True, max_length=250, null=True)),
                ('desk_sections', models.CharField(blank=True, max_length=250, null=True)),
                ('taxation_system', models.CharField(blank=True, max_length=250, null=True)),
                ('count_operation', models.CharField(blank=True, max_length=250, null=True)),
                ('summ', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeskItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_desk', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErroneousOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.CharField(blank=True, max_length=250, null=True)),
                ('date_e', models.CharField(blank=True, max_length=250, null=True)),
                ('summ', models.CharField(blank=True, max_length=250, null=True)),
                ('number_doc', models.CharField(blank=True, max_length=250, null=True)),
                ('condition', models.CharField(blank=True, max_length=250, null=True)),
                ('operation_desk', models.CharField(blank=True, max_length=250, null=True)),
                ('operation_reg', models.CharField(blank=True, max_length=250, null=True)),
                ('type_pay', models.CharField(blank=True, max_length=250, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ident_type', models.CharField(blank=True, max_length=250, null=True)),
                ('caption', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(blank=True, max_length=250, null=True)),
                ('summ', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kontur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bill', models.CharField(blank=True, max_length=250, null=True)),
                ('id_ticket', models.CharField(blank=True, max_length=200, null=True)),
                ('tariff', models.CharField(blank=True, max_length=200, null=True)),
                ('ticket_validity_date', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_ticket_passage', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassagesTurnstile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_timestamp', models.CharField(blank=True, max_length=250, null=True)),
                ('id_point', models.CharField(blank=True, max_length=250, null=True)),
                ('id_ter_from', models.CharField(blank=True, max_length=250, null=True)),
                ('id_ter_to', models.CharField(blank=True, max_length=250, null=True)),
                ('identifier_value', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportZDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=250, null=True)),
                ('condition', models.CharField(blank=True, max_length=250, null=True)),
                ('desk', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('number_fr', models.CharField(blank=True, max_length=250, null=True)),
                ('open_sm', models.CharField(blank=True, max_length=250, null=True)),
                ('operator_open', models.CharField(blank=True, max_length=250, null=True)),
                ('close_sm', models.CharField(blank=True, max_length=250, null=True)),
                ('operator_close', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_use', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleIdent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_s', models.CharField(blank=True, max_length=250, null=True)),
                ('type_s', models.CharField(blank=True, max_length=250, null=True)),
                ('hardware_code', models.CharField(blank=True, max_length=250, null=True)),
                ('user_code', models.CharField(blank=True, max_length=250, null=True)),
                ('condition', models.CharField(blank=True, max_length=250, null=True)),
                ('desk', models.CharField(blank=True, max_length=250, null=True)),
                ('bill', models.CharField(blank=True, max_length=250, null=True)),
                ('service', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesByCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(blank=True, max_length=250, null=True)),
                ('count', models.CharField(blank=True, max_length=250, null=True)),
                ('summ', models.CharField(blank=True, max_length=250, null=True)),
                ('discount', models.CharField(blank=True, max_length=250, null=True)),
                ('all_s', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesByPositionsStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=250, null=True)),
                ('position', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.CharField(blank=True, max_length=250, null=True)),
                ('count', models.CharField(blank=True, max_length=250, null=True)),
                ('summ', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesBySno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('caption', models.CharField(blank=True, max_length=250, null=True)),
                ('count', models.CharField(blank=True, max_length=250, null=True)),
                ('summ', models.CharField(blank=True, max_length=250, null=True)),
                ('discount', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryReportDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_desk', models.CharField(blank=True, max_length=250, null=True)),
                ('operation_reg', models.CharField(blank=True, max_length=250, null=True)),
                ('view_pay', models.CharField(blank=True, max_length=250, null=True)),
                ('count_operation', models.CharField(blank=True, max_length=250, null=True)),
                ('summ', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('the_amount_of_corrective_operations', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(blank=True, max_length=250, null=True)),
                ('pay', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
