# Generated by Django 4.1.2 on 2022-11-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_baloon_date_bill_alter_baloon_id_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baloon',
            name='date_bill',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='kontur',
            name='date_bill',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='kontur',
            name='date_of_ticket_passage',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='kontur',
            name='ticket_validity_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
