# Generated by Django 4.1.2 on 2022-12-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_tarifftypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentSalesStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=250, null=True)),
                ('count', models.CharField(blank=True, max_length=250, null=True)),
                ('summ', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
