# Generated by Django 4.1.2 on 2022-12-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_identsalesstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentSalesByTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff', models.CharField(blank=True, max_length=250, null=True)),
                ('limit', models.CharField(blank=True, max_length=250, null=True)),
                ('used', models.CharField(blank=True, max_length=250, null=True)),
                ('remains', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
