# Generated by Django 4.1.2 on 2022-11-11 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_baloon_date_bill_alter_kontur_date_bill_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baloon',
            options={'verbose_name': 'таблица балона', 'verbose_name_plural': 'таблицы балона'},
        ),
    ]
