# Generated by Django 4.1.2 on 2022-11-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_baloon_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassagesTurnstile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_timestamp', models.CharField(blank=True, max_length=250, null=True)),
                ('id_point', models.CharField(blank=True, max_length=250, null=True)),
                ('id_ter_from', models.CharField(blank=True, max_length=250, null=True)),
                ('id_ter_to', models.CharField(blank=True, max_length=250, null=True)),
                ('identifier_value', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'проходы через турникет',
                'verbose_name_plural': 'проходы через турникет',
            },
        ),
    ]
