# Generated by Django 4.1.2 on 2022-12-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_passageparkgorky'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passagesturnstile',
            name='id_ter_from',
        ),
        migrations.RemoveField(
            model_name='passagesturnstile',
            name='id_ter_to',
        ),
    ]
