# Generated by Django 4.1.2 on 2022-11-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_passagesturnstile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_use', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'правила пользования',
                'verbose_name_plural': 'правила пользованпя',
            },
        ),
    ]
