# Generated by Django 4.1.2 on 2022-11-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_rulelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'услугу',
                'verbose_name_plural': 'услуги',
            },
        ),
    ]
