# Generated by Django 4.1.2 on 2022-11-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_servicelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_desk', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'касса',
                'verbose_name_plural': 'кассы',
            },
        ),
    ]
