# Generated by Django 4.1.2 on 2022-12-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_titlepassageparkgorky'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevGroupItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dg_it', models.CharField(blank=True, max_length=250, null=True)),
                ('id_dg', models.CharField(blank=True, max_length=250, null=True)),
                ('id_point', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dg', models.CharField(blank=True, max_length=250, null=True)),
                ('caption', models.CharField(blank=True, max_length=250, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
