# Generated by Django 4.1.2 on 2022-11-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_deskitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportZDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_row', models.CharField(blank=True, max_length=250, null=True)),
                ('td_row', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryReportDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_row', models.CharField(blank=True, max_length=250, null=True)),
                ('td_row', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
