# Generated by Django 4.1.2 on 2022-12-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_devgroupitems_devgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='passagesturnstile',
            name='id_res',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
