# Generated by Django 4.1.2 on 2022-11-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_reportzdesk_summaryreportdesk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportzdesk',
            old_name='td_row',
            new_name='close_sm',
        ),
        migrations.RenameField(
            model_name='reportzdesk',
            old_name='th_row',
            new_name='condition',
        ),
        migrations.AddField(
            model_name='reportzdesk',
            name='desk',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reportzdesk',
            name='number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reportzdesk',
            name='number_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reportzdesk',
            name='open_sm',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reportzdesk',
            name='operator_close',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reportzdesk',
            name='operator_open',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reportzdesk',
            name='type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
