# Generated by Django 4.1.2 on 2022-11-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_rename_td_row_reportzdesk_close_sm_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportZDesk',
        ),
    ]
