# Generated by Django 4.1.2 on 2022-11-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_delete_reportzdesk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportZDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=250, null=True)),
                ('condition', models.CharField(blank=True, max_length=250, null=True)),
                ('desk', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('number_fr', models.CharField(blank=True, max_length=250, null=True)),
                ('open_sm', models.CharField(blank=True, max_length=250, null=True)),
                ('operator_open', models.CharField(blank=True, max_length=250, null=True)),
                ('close_sm', models.CharField(blank=True, max_length=250, null=True)),
                ('operator_close', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
