# Generated by Django 4.1.2 on 2022-11-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_reportzdesk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summaryreportdesk',
            old_name='td_row',
            new_name='count_operation',
        ),
        migrations.RenameField(
            model_name='summaryreportdesk',
            old_name='th_row',
            new_name='operation_desk',
        ),
        migrations.AddField(
            model_name='summaryreportdesk',
            name='operation_reg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='summaryreportdesk',
            name='summ',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='summaryreportdesk',
            name='view_pay',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
