# Generated by Django 4.1.2 on 2022-11-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_rename_td_row_summaryreportdesk_count_operation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErroneousOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.CharField(blank=True, max_length=250, null=True)),
                ('date_e', models.CharField(blank=True, max_length=250, null=True)),
                ('summ', models.CharField(blank=True, max_length=250, null=True)),
                ('number_doc', models.CharField(blank=True, max_length=250, null=True)),
                ('condition', models.CharField(blank=True, max_length=250, null=True)),
                ('operation_desk', models.CharField(blank=True, max_length=250, null=True)),
                ('operation_reg', models.CharField(blank=True, max_length=250, null=True)),
                ('type_pay', models.CharField(blank=True, max_length=250, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
