# Generated by Django 4.1.2 on 2022-11-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_erroneousoperations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('the_amount_of_corrective_operations', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
