# Generated by Django 4.1.2 on 2022-11-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_summmoney'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(blank=True, max_length=250, null=True)),
                ('pay', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
