# Generated by Django 4.1.2 on 2022-11-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_decodingofdesksectionsandtaxgroups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformationAboutTheDeskRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_a', models.CharField(blank=True, max_length=250, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
