# Generated by Django 4.1.2 on 2022-11-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_additionalinformationaboutthedeskregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ident_type', models.CharField(blank=True, max_length=250, null=True)),
                ('caption', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
