# Generated by Django 4.1.2 on 2022-11-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_identtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleIdent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_s', models.CharField(blank=True, max_length=250, null=True)),
                ('type_s', models.CharField(blank=True, max_length=250, null=True)),
                ('hardware_code', models.CharField(blank=True, max_length=250, null=True)),
                ('user_code', models.CharField(blank=True, max_length=250, null=True)),
                ('condition', models.CharField(blank=True, max_length=250, null=True)),
                ('desk', models.CharField(blank=True, max_length=250, null=True)),
                ('bill', models.CharField(blank=True, max_length=250, null=True)),
                ('service', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
