# Generated by Django 4.1.2 on 2022-12-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_saleident'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesByCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(blank=True, max_length=250, null=True)),
                ('count', models.CharField(blank=True, max_length=250, null=True)),
                ('summ', models.CharField(blank=True, max_length=250, null=True)),
                ('discount', models.CharField(blank=True, max_length=250, null=True)),
                ('all_s', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
